services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password123
      MYSQL_DATABASE: todo_app
      MYSQL_USER: nextjs_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network: